on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: ${{ secrets.ACCESSKEY }} 
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: '<region>'

      - name: Download Folder and Exclude Some Objects from OBS
        uses: huaweicloud/obs-helper@v1.4.0
        with:
          bucket_name: '<bucket-name>'
          obs_file_path: src/download
          local_file_path: ./resource/download
          operation_type: download
          include_self_folder: yes
          exclude: |
            src/download/obsFolder1/obsFile1-1.txt
            src/download/obsFolder2