on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: ${{ secrets.ACCESSKEY }} 
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: '<region>'
        
      - name: Upload Folder to OBS
        uses: huaweicloud/obs-helper@v1.4.0
        id: upload_multi_files_to_obs
        with:
          bucket_name: '<bucket-name>'
          local_file_path: |
            ./resource/upload/folder1
            ./resource/upload/folder2
            ./resource/upload/file1.txt    
          obs_file_path: src/upload 
          operation_type: upload
          include_self_folder: true